---
deployment:
  tasks:
    - export REPOPATH=/home/barsmebelb/repositories/weblayout__BARSMebel/*
    - export SITEPATH=/home/barsmebelb/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
